name: '[builder] CI for releases'
on:
    push:
        branches:
            - master
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                buildx-version: latest
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/amd64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag dpippenger/fluentd:latest
        - 
            name: Scan Image Using Anchore
            uses: anchore/scan-action@master
            with:
                image-reference: "dpippenger/fluentd:latest"
                dockerfile-path: "./Dockerfile"
                fail-build: false
        - 
           name: anchore inline scan JSON results
           run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
